### ISSUE TITLE
RHPDS bastion provisioner fails while setting cluster URL.

### ISSUE THREAD

**Issue by mamurak** [rh-emea-sa/rhpds-bastion-setup#3]
Error:

TASK [Set Cluster URL as fact] ********************************************************************************************************
fatal: [bastion.5n4ng.sandbox1390.opentlc.com]: FAILED! => {"msg": "template error while templating string: no filter named 'ansible.builtin.split'. String: {{ ocp_api_url | urlsplit('hostname') | ansible.builtin.split('.') }}"}

environment:
ansible --version
ansible 2.9.9
  config file = /home/mmurakam/.ansible.cfg
  configured module search path = ['/home/mmurakam/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mmurakam/.local/lib/python3.6/site-packages/ansible
  executable location = /home/mmurakam/.local/bin/ansible
  python version = 3.6.8 (default, Jun 14 2022, 12:54:58) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)]

**Comment by kubealex** [comment]
Solved by using a custom Execution Environment to avoid version/modules/collection mismatch. 
Documentation adjusted accordingly in the README.
